model:
  conv1_args: [1, 32, 3, 1]
  conv2_args: [32, 64, 3,1]
  fc1_args: [9216, 128]
  fc2_args: [128, 10]
  dropout_rate1: 0.25
  dropout_rate2: 0.5
training_dataset:
  root: ./data
  target_dataset: "MNIST"
  transform: [ToTensor,]
  train: True
  download: True
  size: 6000
test_dataset:
  root: ./data
  target_dataset: "MNIST"
  transform: [ToTensor,]
  train: False
  download: True
  size: 1200
training:
  device: "cuda"
  epochs: 10
  batch_size: 32
  learning_rate: 0.01
  split_ratio: [0.8, 0.2]